PROJECT_NAME := carbon-carp_fmcomms5
REVISION := rev4.1
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS := hdl-compat-fmcomms5-carbon
M_DEPS :=

include ../../../common/carbon-carp/$(REVISION)/scripts/carbon-carp.mk
include ../../scripts/fmcomms5_proj.mk
