# SPDX-License-Identifier: Apache-2.0

PROJECT_NAME := carbon_fmcomms5
REVISION := rev4
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS := hdl-compat-fmcomms5-carbon
M_DEPS :=

include ../../../common/carbon/$(REVISION)/scripts/carbon.mk
include ../../scripts/fmcomms5_proj.mk
